Update README
overleaf/clsi pull request #213
Opened 2021-03-10 22:41 UTC by aeaton-overleaf

This updates the README with instructions for running the CLSI in Docker using the `texlive/texlive` image for sibling containers.

2021-03-11 09:36 UTC, mans0954 commented
3009 has never been the CLSI port - it's the filestore port. I must have been confused when I added that to the notes!

2021-03-11 09:47 UTC, mans0954 commented
There are a number of environment variables missing from the list. These are the ones I found going through the setting file:
```
ALLOWED_COMPILE_GROUPS
ALLOWED_IMAGES
CATCH_ERRORS
COMPILE_GROUP_DOCKER_CONFIGS
COMPILES_HOST_DIR
COMPILE_SIZE_LIMIT
DOCKER_RUNNER
DOCKER_RUNTIME
FILESTORE_DOMAIN_OVERRIDE
FILESTORE_PARALLEL_FILE_DOWNLOADS
FILESTORE_PARALLEL_SQL_QUERY_LIMIT
LISTEN_ADDRESS
PROCESS_LIFE_SPAN_LIMIT_MS
SENTRY_DSN
SMOKE_TEST
SQLITE_PATH
SYNCTEX_BIN_HOST_PATH
TEXLIVE_IMAGE
TEX_LIVE_IMAGE_NAME_OVERRIDE
TEXLIVE_IMAGE_USER
TEXLIVE_OPENOUT_ANY
```

2021-03-11 11:35 UTC, mans0954 commented
These instructions don't work as is on Linux, because the `root` user in the texlive image gets mapped to the root user on the host. A workaround is to do something like:
```
sudo chown -R mans0954:root compiles/
sudo chmod g+w -R compiles/
```

2021-03-11 11:44 UTC, mans0954 requested changes
Thanks very much for picking this up! I think the path to the default settings file should be changed. If you've got the time it would be great to add the extra env vars in to the README.

I've never found an entirely satisfactory solution to the Linux file permission mapping. In the dev environment we fudged around it by changing the uid of my Ubuntu account from 1001 to 1000 to match the `tex` user in our `gcr.io/overleaf-ops/texlive-full` image.

2021-03-11 11:47 UTC, hubgit commented
> These instructions don't work as is on Linux, because the root user in the texlive image gets mapped to the root user on the host.

I couldn't find a more appropriate user in the `texlive` image, but if there's a suggestion that works here I'd be happy to update the command.

2021-03-11 11:48 UTC, hubgit commented
> it would be great to add the extra env vars in to the README.

If you wouldn't mind adding them in a separate PR that might be better, as I'm not sure of the description needed for each one.

2021-03-11 11:49 UTC, aeaton-overleaf commented
> These instructions don't work as is on Linux, because the root user in the texlive image gets mapped to the root user on the host.

I couldn't find a more appropriate user in the texlive image, but if there's a suggestion that works here I'd be happy to update the command.

2021-03-11 11:49 UTC, aeaton-overleaf commented
> it would be great to add the extra env vars in to the README.

If you wouldn't mind adding them in a separate PR that might be better, as I'm not sure of the description needed for each one.

2021-03-11 11:50 UTC, aeaton-overleaf commented on README.md
Done

2021-03-11 11:51 UTC, aeaton-overleaf commented on README.md
> +The CLSI will use a SQLite database by default, but you can optionally set up a MySQL database and then fill in the database name, username and password in the config file at `config/settings.develop
Done

2021-03-11 12:06 UTC, jdleesmiller commented
> `sudo chown -R mans0954:root compiles/`

It may be worth asking... do we need to bind mount `compiles` at all? I think it's basically ephemeral data. Keeping it in a volume instead of a bind mount might avoid some complexity here. (Also, I think it would be fine for the `/compiles` data to live in `/tmp` for the same reason, and making a volume for `/tmp` is a fairly standard thing to do.) But, that could all be separate to these README improvements!

2021-03-17 13:07 UTC, mans0954 commented
> It may be worth asking... do we need to bind mount `compiles` at all? I think it's basically ephemeral data. Keeping it in a volume instead of a bind mount might avoid some complexity here. (Also, I think it would be fine for the `/compiles` data to live in `/tmp` for the same reason, and making a volume for `/tmp` is a fairly standard thing to do.) 

Currently a folder on the host (e.g. `$PWD/compiles`) gets mounted into CLSI and then project subfolders (e.g. `$PWD/compiles/1234`) get mounted into the TeX Live container. Presumably DockerRunner would need to create per-project volumes in order to achieve the same level of security as we have at the moment, as I don't think you can mount a path within a volume into a container? Possibly sharing a single volume between the CLSI and all the TeX Live containers would be acceptable in the dev environment?

> But, that could all be separate to these README improvements!

Is it worth writing up an issue for this?

2021-03-17 13:22 UTC, aeaton-overleaf commented
> I don't think you can mount a path within a volume into a container?

Right, it doesn't seem to be possible. https://github.com/moby/moby/issues/32582

You could mount the whole named volume somewhere without read access and symlink the project folder into somewhere with read access, but that would be a bit risky.

2021-03-17 21:05 UTC, jdleesmiller commented
> mounted into the TeX Live container

Good points, thanks! I think we can forget about my comment, in that case. I have given the upstream issue a 👍 .

2021-03-18 09:15 UTC, mans0954 commented
> Good points, thanks! I think we can forget about my comment, in that case. I have given the upstream issue a  .

Okay, not quite sure where to go next with this. There are some good improvements to the README in the PR, but I feel we should at least acknowledge that the instructions won't work if followed literally on most Linux setups.

2021-03-18 09:51 UTC, aeaton-overleaf commented
To make it work on Linux, is it enough to comment out the `-e TEXLIVE_IMAGE_USER=root \` line? I could do that and add a comment about enabling it for macOS.

2021-03-18 09:56 UTC, aeaton-overleaf commented
Updated to move the `TEXLIVE_IMAGE_USER` into the macOS-specific instructions.

2021-03-18 11:15 UTC, mans0954 commented
> To make it work on Linux, is it enough to comment out the `-e TEXLIVE_IMAGE_USER=root \` line? I could do that and add a comment about enabling it for macOS.

Unfortunately that gives the error `(HTTP code 500) server error - linux spec user: unable to find user tex: no matching entries in passwd file ` because `TEXLIVE_IMAGE_USER` defaults to `tex` and there is no `tex` user in the TeX Live image.

Possibly one could provide instructions for building an image based on Tex Live which contained an additional user. I think you would still need to make the uids of the users in the images match with the uid of the host user.

2021-03-18 11:32 UTC, aeaton-overleaf commented
If it's not currently possible to make this work on Linux then I'll propose merging this and updating it when there's a solution.

2021-03-18 11:34 UTC, aeaton-overleaf commented
@mans0954 Would documenting this workaround that you proposed earlier make sense instead?

```sh
sudo chown -R mans0954:root compiles/
sudo chmod g+w -R compiles/
```

2021-03-18 14:25 UTC, mans0954 commented
> @mans0954 Would documenting this workaround that you proposed earlier make sense instead?
> 
> ```shell
> sudo chown -R mans0954:root compiles/
> sudo chmod g+w -R compiles/
> ```

Yes, I think that was what I originally had in mind!

2021-03-19 12:09 UTC, aeaton-overleaf commented
Updated with instructions for changing permissions on the `compiles` folder on Linux.

2021-03-19 12:28 UTC, mans0954 commented
> Updated with instructions for changing permissions on the `compiles` folder on Linux.

To be honest, it's a bit more complicated than that. I'll try to write something up.

2021-03-19 14:34 UTC, mans0954 approved these changes
I've written something about the permissions issue on Linux. It's complicated as some distros use 1000 as the uid for the first normal user and some use 1001.

2021-03-23 09:41 UTC, merged