Add missing environment variables to CLSI README.
overleaf/clsi pull request #216
Opened 2021-03-16 15:08 UTC by mans0954

Requested change to https://github.com/overleaf/clsi/pull/213

I couldn't find a link to authoritative documentation as to what the `openout_any` env variable actually does. CC @GrahamMDouglas

2021-03-16 15:14 UTC, aeaton-overleaf requested changes
Thanks! Just a couple of proof-reading nitpicks.

2021-03-16 15:14 UTC, aeaton-overleaf commented on README.md
> +* `TEX_LIVE_IMAGE_NAME_OVERRIDE` - The name of the registry for the docker image e.g. `gcr.io/overleaf-ops`
Nitpick: "docker" => "Docker"

2021-03-16 15:14 UTC, aeaton-overleaf commented on README.md
> +* `TEXLIVE_OPENOUT_ANY` - Sets the `openout_any` environment variable for Tex Live
Nitpick: "Tex Live" and "TEXLIVE" => "TeX Live"

2021-03-16 16:06 UTC, aeaton-overleaf approved these changes

2021-03-16 16:06 UTC, merged

2021-03-19 10:36 UTC, mans0954 commented
> 'openout_any' is discussed in the Web2C documentation, this section: http://tug.org/texinfohtml/web2c.html#tex-invocation. Look for the sentence starting "TeX can write output files, via the \openout primitive..."

Thanks! I've linked to that documentation in the README.